[build-system]
requires = ["setuptools==82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "ci-lab-1-flask"
version = "0.1.0"
description = "Minimal Flask application for the CI laboratory"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements-runtime.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["app", "app.*"]
namespaces = false
