apiVersion: v1
kind: Service
metadata:
  name: ci-lab-flask
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: ci-lab-flask
  ports:
    - name: http
      port: 5000
      targetPort: http